### ISSUE TITLE
Missing resistors in bom

### ISSUE THREAD

**Issue by LokiMetaSmith** [PubInv/NASA-COG#211]
![PXL_20230906_194246007](https://github.com/PubInv/NASA-COG/assets/5054116/e7cee0c5-6816-40ae-a546-b7019f063f3e)

1R0 and 1R some populated and some didn't.

Will need to apply jumpers where nessisary

**Comment by ForrestErickson** [comment]
Back on about Aug 30 or so, I put 1K resistors on these pins during my clean up of the BOM for JLCPCB parts.
Leakage on these pins is specified at 1uA so 1K should be fine.

![image](https://github.com/PubInv/NASA-COG/assets/5836181/0a8b407b-f745-42a7-8c98-b8a9c82ee0ac)

**Comment by LokiMetaSmith** [comment]
These were jumpered, leaving issue for control v2

**Comment by ForrestErickson** [comment]
FYI, Work I did on the schematic (BOM) after the V1 assemblies was ordered filled in these parts and more.
![image](https://github.com/PubInv/NASA-COG/assets/5836181/f132a25a-1e4d-46e2-ac09-7ed45a5c8005)
Specifically I used 1K so that even if the jumpers on the Adafruit assemblies were not cut correctly there would be no smoke let out of anything.

**Comment by RobertLRead** [comment]
I assume this is closable.
